# Generated by Django 3.2.9 on 2021-11-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_usuarios_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo_usuario', models.CharField(max_length=50)),
            ],
        ),
    ]
