# Generated by Django 3.2.6 on 2021-11-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.IntegerField(),
        ),
    ]
