# Generated by Django 3.2.6 on 2021-11-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_alter_usuarios_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_modelo', models.CharField(max_length=50)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.marca')),
            ],
        ),
    ]
