# Generated by Django 3.2.6 on 2021-11-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_color_marca_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('transmision_vehiculo', models.CharField(max_length=50)),
                ('motor_vehiculo', models.IntegerField()),
                ('anio_vehiculo', models.IntegerField()),
                ('nro_chassis_vehiculo', models.CharField(max_length=100)),
                ('precio_costo', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.color')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.marca')),
            ],
        ),
    ]
