# Generated by Django 3.2.6 on 2021-11-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='id_modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.modelo'),
        ),
    ]
