# Generated by Django 3.2.6 on 2021-11-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_vehiculo_id_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado_vehiculo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
