# Generated by Django 3.2.8 on 2021-12-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_vehiculo_estado_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_cliente',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo_documento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('documento_cliente', models.CharField(max_length=10)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('genero_cliente', models.IntegerField()),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.tipo_cliente')),
            ],
        ),
    ]
