# Generated by Django 3.2.6 on 2021-12-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tipo_cliente',
            new_name='tipo_documento',
        ),
    ]
