# Generated by Django 3.2.6 on 2021-12-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_rename_tipo_cliente_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.pais'),
        ),
    ]
