# Generated by Django 3.2.8 on 2021-12-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_auto_20211210_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='id_pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.pais'),
        ),
    ]
