# Generated by Django 3.2.6 on 2022-01-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0014_cliente_estado_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('ruc_proveedor', models.CharField(max_length=20)),
                ('razon_social_proveedor', models.CharField(max_length=50)),
                ('direccion_proveedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='timbrado',
            fields=[
                ('nro_timbrado', models.IntegerField(primary_key=True, serialize=False)),
                ('fch_vencimiento_timbrado', models.DateField()),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.proveedor')),
            ],
        ),
    ]
