# Generated by Django 3.2.6 on 2022-02-02 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0018_alter_proveedor_telefono_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura_compra',
            fields=[
                ('id_factura_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nro_factura_compra', models.IntegerField()),
                ('fch_factura_compra', models.DateField()),
                ('condicion_factura_compra', models.IntegerField()),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.proveedor')),
                ('id_timbrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.timbrado')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.vehiculo')),
            ],
        ),
    ]
