# Generated by Django 3.2.6 on 2022-02-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0019_factura_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura_compra',
            old_name='id_timbrado',
            new_name='nro_timbrado',
        ),
    ]
