# Generated by Django 3.2.6 on 2022-02-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0019_factura_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fch_apertura_caja', models.DateField()),
                ('inicio_caja', models.IntegerField()),
                ('fch_cierre_caja', models.DateField(null=True)),
                ('cierre_caja', models.IntegerField(null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='timbrado_parametros',
            fields=[
                ('nro_timbrado_parametros', models.IntegerField(primary_key=True, serialize=False)),
                ('fch_vencimiento_timbrado_parametros', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='factura_compra',
            old_name='id_timbrado',
            new_name='nro_timbrado',
        ),
        migrations.CreateModel(
            name='factura_venta',
            fields=[
                ('id_factura_venta', models.AutoField(primary_key=True, serialize=False)),
                ('nro_factura_venta', models.IntegerField()),
                ('fch_factura_venta', models.DateField()),
                ('condicion_factura_venta', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.cliente')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.vehiculo')),
                ('nro_timbrado_parametros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.timbrado_parametros')),
            ],
        ),
        migrations.CreateModel(
            name='factura_parametros',
            fields=[
                ('id_factura_parametros', models.AutoField(primary_key=True, serialize=False)),
                ('nro_inicio_factura_parametros', models.IntegerField()),
                ('nro_actual_factura_parametros', models.IntegerField()),
                ('nro_fin_factura_parametros', models.IntegerField()),
                ('nro_timbrado_parametros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.timbrado_parametros')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_caja',
            fields=[
                ('id_detalle_caja', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento_detalle_caja', models.IntegerField()),
                ('descripcion_detalle_caja', models.CharField(max_length=100)),
                ('monto_detalle_caja', models.IntegerField()),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.caja')),
            ],
        ),
    ]
