# Generated by Django 3.2.6 on 2022-02-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0020_auto_20220207_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_venta',
            name='estado_factura_venta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura_venta',
            name='iva10_factura_venta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura_venta',
            name='subtotal_factura_venta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura_venta',
            name='total_factura_venta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
