# Generated by Django 3.2.6 on 2022-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0021_auto_20220208_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_venta',
            name='monto_cobrado_factura_venta',
            field=models.IntegerField(null=True),
        ),
    ]
