# Generated by Django 3.2.6 on 2022-02-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0022_factura_venta_monto_cobrado_factura_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_venta',
            name='iva10_factura_venta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura_venta',
            name='monto_cobrado_factura_venta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='factura_venta',
            name='subtotal_factura_venta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura_venta',
            name='total_factura_venta',
            field=models.FloatField(),
        ),
    ]
