# Generated by Django 3.2.6 on 2022-02-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0022_caja_fch_cierre_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='cierre_caja',
            field=models.IntegerField(null=True),
        ),
    ]
