# Generated by Django 3.2.6 on 2022-02-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0024_factura_venta_fch_cobrado_factura_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='cierre_caja',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='inicio_caja',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalle_caja',
            name='monto_detalle_caja',
            field=models.FloatField(),
        ),
    ]
