# Generated by Django 3.2.6 on 2022-02-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0025_auto_20220208_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagare',
            fields=[
                ('id_pagare', models.AutoField(primary_key=True, serialize=False)),
                ('deuda_total_pagare', models.IntegerField()),
                ('fecha_inicio_pagare', models.DateField()),
                ('fecha_final_pagare', models.DateField()),
                ('estado_pagare', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.cliente')),
                ('id_factura_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.factura_venta')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_pagare',
            fields=[
                ('id_pagare_detalle_pagare', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cuota_detalle_pagare', models.IntegerField()),
                ('fch_vencimiento_detalle_pagare', models.DateField()),
                ('monto_pagare_detalle', models.FloatField()),
                ('intereses_pagare_detalle', models.FloatField(null=True)),
                ('fch_pago_detalle_pagare', models.DateField(null=True)),
                ('id_pagare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.pagare')),
            ],
        ),
    ]
