# Generated by Django 3.2.6 on 2022-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0026_detalle_pagare_pagare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagare',
            name='fecha_final_pagare',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='fecha_inicio_pagare',
            field=models.DateField(null=True),
        ),
    ]
