# Generated by Django 3.2.6 on 2022-02-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0029_pagare_total_pagares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagare',
            name='cancelados_pagares',
            field=models.IntegerField(null=True),
        ),
    ]
